// Main localities/areas of Hyderabad for agent location selection
export const HYDERABAD_LOCATIONS = [
  "Madhapur",
  "Gachibowli",
  "Kondapur",
  "Kukatpally",
  "Miyapur",
  "Manikonda",
  "Kokapet",
  "Financial District",
  "Banjara Hills",
  "Jubilee Hills",
  "Ameerpet",
  "Begumpet",
  "Secunderabad",
  "Somajiguda",
  "Mehdipatnam",
  "Tolichowki",
  "Attapur",
  "Narsingi",
  "Puppalguda",
  "Shamshabad",
  "LB Nagar",
  "Dilsukhnagar",
  "Uppal",
  "Habsiguda",
  "Tarnaka",
  "Sainikpuri",
  "Kompally",
  "Alwal",
  "Malkajgiri",
  "Bowenpally",
  "Bachupally",
  "Nizampet",
  "Pragathi Nagar",
  "Chandanagar",
  "Lingampally",
  "Nallagandla",
  "Tellapur",
  "Patancheru",
  "Mokila",
  "Shankarpally",
  "Charminar",
  "Abids",
  "Nampally",
  "Himayat Nagar",
  "Khairatabad",
  "Yousufguda",
  "Srinagar Colony",
  "Balapur",
  "Nagole",
  "Vanasthalipuram",
  "Hayathnagar",
  "Ghatkesar",
  "Pocharam",
  "ECIL",
  "AS Rao Nagar",
  "Moosapet",
  "Balanagar",
  "Jeedimetla",
  "Dundigal",
  "Medchal",
  "Shamirpet",
  "Adibatla",
  "Tukkuguda",
  "Maheshwaram",
  "Shadnagar",
  "Serilingampally",
  "Raidurgam",
  "Nanakramguda",
  "Khajaguda",
  "Gopanpally",
  "Osman Nagar",
  "Bandlaguda",
  "Kismatpur",
  "Rajendra Nagar",
  "Budvel",
  "Kothapet",
  "Malakpet",
  "Amberpet",
  "Musheerabad",
  "Kachiguda",
  "Sultan Bazaar",
] as const;

export type HyderabadLocation = typeof HYDERABAD_LOCATIONS[number];
